name: ContainerExerciseWF

on: 
  workflow_dispatch:

jobs:
  First_Container_job:
    runs-on: ubuntu-latest
    container: #By default, Docker-container is 
      image: node:13.5.0-alpine3.10 #The image (13.5.0-alpine3.10) is fetched from the public Docker Hub -registry. To access that, 
      #a Docker-ID is needed (node). Workflow creator needs no account, only the Docker-ID and image-ID.

    steps:
      - name: log some info
        run: |
          node -v
          cat /etc/os-release
      
      - name: docker-step
        uses: docker://node:16.15-alpine3.14
        run: |
          node -v
          cat /etc/os-release