name:  Default and custome variables exercise

on:
  push:

  workflow_dispatch:

env:
  WF_level_env: Workflow custom variable
  Hidden_WF_variable: ${{ secrets.HIDDEN_VARIABLE }} #Not displayed in output

jobs:
  myCustomVariables:
    runs-on: windows-latest
    env: 
      Job_level_variable: Job-level custom variable
    steps:
      - name: Log names
        env: 
          Step_level_variable: Step-level custom variable
        run: |
          echo "Workflow env: $env:WF_level_env"
          echo "My hidden variable never to be displayed: $env:Hidden_WF_variable"
          echo "Job env: $env:Job_level_variable"
          echo "Step env: $env:Step_level_variable"
      - name: Show me carried job-level
        run: echo "Job-level vatriable carried over, look! $env:Job_level_variable"
  
  VariableCarring:
    runs-on: windows-latest
    steps:
      - name: Check variable carrying
        run: |
          echo "Workflow env should be displayed: $env:WF_level_env"
          echo "Let me know if job-level variable is over-carried: $env:Job_level_variable"
          echo "Step env shouldn't be carried and so blank next: $env:Step_level_variable"

  myDefaultVariables:
    runs-on: macos-latest
    steps:
      - name: display default variable values
        run: |
          echo "HOME: $HOME"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_Action: $GITHUB_ACTION"
          echo "GITHUB_Actions: $GITHUB_ACTIONS"
          echo "GITHUB_Action path: $GITHUB_ACTION_PATH"
          echo "GITHUB_Action repo: $GITHUB_ACTION_REPOSITORY"
          echo "GITHUB_repo: $GITHUB_REPOSITORY"