name: Context and expression testing
#Contexts are collections of functions that shoiw information about your workflow when they get executed.
# Expression is a definition for a variable or function that is evaluated.
# The purpose is to access information about your workflow, jobs, steps, 
# environments, and runs. See more at https://docs.github.com/en/actions/learn-github-actions/contexts
# It uses syntax ${{ context_and_specification }}.
on:
  #push:
  workflow_dispatch:

jobs:
  Jason_contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        if: always()
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        if: github.actor == 'PaavoBugHunter'
        run: echo 'BugHunter is actor and ${{ toJSON(job) }}'
      - name: Dump steps context
        if: success() #If-key and step-status function
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        if: always()
        run: echo '${{ toJSON(runner) }}'

  Function_expressions:
    runs-on: macos-latest
    if: github.event_name == 'push' #If-key and job-status function
    steps:
      - name: Display truth
        env:
          my_key: ${{ contains('Paavo', 'av' ) }}
        run: echo "$my_key"
