name: Multiple OSes for workflow
# A job is set-up to run on mulitple operating systems with jobs -> job_ID -> strategy -> matrix command-chain.
# A matrix can include combinations of opersating systems and their versions

on:
  push:
  workflow_dispatch:

jobs:
  job_for_the_matrix:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        exclude:
          - os: ubuntu-latest #Excludes execution for matrix-unit ubuntu-latest
        include:
          - os: windows-latest
            is_windows: 'True' #Includes variable is_windows to windows-latest matrix-unit
    runs-on: ${{ matrix.os }}
    env:
      is_windows_true: ${{ matrix.is_windows }}

    steps:
      - name: Log mac version
        if: matrix.os == 'macos-latest'
        run: |
          sw_vers -productVersion
          echo $is_windows_true

      - name: Log ubuntu version
        if: matrix.os == 'ubuntu-latest'
        run: lsb_release -d

      - name: Log Windows version
        if: matrix.os == 'windows-latest'
        run: |
          Get-ComputerInfo | select OsHardwareAbstractionLayer
          echo $is_windows_true
