name: Multiple OSes for workflow

on:
  push:
  workflow_dispatch:

jobs:
  job_for_the_matrix:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Log mac version
        if: matrix.os == 'macos-latest'
        run: sw_vers -productVersion

      - name: Log ubuntu version
        if: matrix.os == 'ubuntu-latest'
        run: lsb_release -d

      - name: Log Windows version
        if: matrix.os == 'windows-latest'
        run: Get-ComputerInfo | select OsHardwareAbstractionLayer

      #- name: Catch job's os
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: ${{ matrix.os }}
        
      #- name: Display os-version
      #  run: node -v
